name: aad_oauth
description: A Flutter OAuth package for performing user authentication against
  Azure Active Directory OAuth2 v2.0 endpoint.
version: 0.4.0
homepage: https://github.com/Earlybyte/aad_oauth
publish_to: none

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage: ^5.0.0-beta.5
  flutter_webview_plugin: 
    git:
      url: https://github.com/kiratheone/flutter_webview_plugin.git
  http: ^0.13.3
  pedantic: ^1.11.1
  shared_preferences: ^2.0.13

dev_dependencies:
  flutter_test:
    sdk: flutter
